# Generated by Django 4.2.7 on 2023-11-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
